channels:
  - conda-forge
dependencies:
<<<<<<< HEAD
  - geopandas==0.14.2
  - ipywidgets==7.8.1
  - matplotlib==3.8.4
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn==0.13.2
=======
  - python=3.12
  - pandas==1.1.0
  - matplotlib==3.3.1
  - seaborn==0.10.0
  - numpy==1.19.1
  - geopandas==0.8.1
>>>>>>> 05250eae6db8f26463e67450857919de8b424b65
  - appmode==0.8.0
  - xlrd==1.2.0
  - descartes==1.1.0
