channels:
  - conda-forge
dependencies:
  - geopandas==0.14.2
  - ipywidgets==7.8.1
  - matplotlib==3.8.4
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn==0.13.2
  - appmode==0.8.0
  - xlrd==1.2.0
  - descartes==1.1.0
